import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedContext } from "@/lib/server/auth";
import {
  createInterviewProof,
  hashAnswer,
} from "@/lib/server/interviewProof";
import { checkRateLimit } from "@/lib/server/rateLimit";
import {
  getBoundedString,
  isPlainObject,
  parseDetectionInput,
  readJsonBody,
} from "@/lib/validation";

const createResponse = (
  userId: string,
  answer: string,
  result: { isAI: boolean; confidence: number; reason: string }
) => ({
  ...result,
  detectionToken: createInterviewProof({
    kind: "detection",
    version: 1,
    userId,
    answerHash: hashAnswer(answer),
    ...result,
    issuedAt: Date.now(),
  }),
});

export async function POST(req: NextRequest) {
  const { user } = await getAuthenticatedContext();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rateLimit = checkRateLimit(
    `detect-ai:${user.id}`,
    70,
    10 * 60 * 1000
  );
  if (!rateLimit.allowed) {
    return NextResponse.json(
      { error: "Too many detection requests. Please wait and try again." },
      {
        status: 429,
        headers: { "Retry-After": String(rateLimit.retryAfterSeconds) },
      }
    );
  }

  const body = await readJsonBody(req);
  if (!body.ok) {
    return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  }

  try {
    const input = parseDetectionInput(body.data);
    if (!input) {
      return NextResponse.json(
        { error: "Invalid detection input." },
        { status: 400 }
      );
    }

    if (input.answer.split(/\s+/).length < 15) {
      return NextResponse.json(
        createResponse(user.id, input.answer, {
          isAI: false,
          confidence: 0,
          reason: "Answer too short to analyze",
        })
      );
    }

    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        createResponse(user.id, input.answer, {
          isAI: false,
          confidence: 0,
          reason: "Detection unavailable",
        })
      );
    }

    const response = await fetch(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "llama-3.1-8b-instant",
          messages: [
            {
              role: "user",
              content: `Analyze whether this interview answer was generated by an AI writing tool.

Answer: ${input.answer}

Gibberish is not AI. Only mark AI when the answer is coherent and shows strong, specific AI-writing signals. Return only:
{"isAI":false,"confidence":0,"reason":"one sentence"}`,
            },
          ],
          max_tokens: 200,
        }),
      }
    );

    if (!response.ok) {
      return NextResponse.json(
        { error: "Detection service failed." },
        { status: 502 }
      );
    }

    const json = await response.json();
    const text = json.choices?.[0]?.message?.content ?? "";
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) {
      return NextResponse.json(
        { error: "Detection returned an invalid response." },
        { status: 502 }
      );
    }

    const raw: unknown = JSON.parse(match[0]);
    if (!isPlainObject(raw)) {
      return NextResponse.json(
        { error: "Detection returned an invalid response." },
        { status: 502 }
      );
    }

    const confidence = Math.min(100, Math.max(0, Number(raw.confidence)));
    const reason = getBoundedString(raw.reason, 1, 500);
    if (
      typeof raw.isAI !== "boolean" ||
      !Number.isFinite(confidence) ||
      !reason
    ) {
      return NextResponse.json(
        { error: "Detection returned an invalid response." },
        { status: 502 }
      );
    }

    return NextResponse.json(
      createResponse(user.id, input.answer, {
        isAI: raw.isAI && confidence >= 85,
        confidence,
        reason,
      })
    );
  } catch {
    return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  }
}
