import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { answer } = await req.json();

    const apiKey = process.env.GROQ_API_KEY;

    if (!apiKey) {
      return NextResponse.json({ error: "Missing API key" }, { status: 500 });
    }

    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "llama-3.1-8b-instant",
        messages: [
          {
            role: "user",
            content: `You are an AI detection expert. Analyze the following interview answer and determine if it was written by a human or generated by AI.

Answer: "${answer}"

Look for these AI indicators:
- Overly structured with perfect bullet points or numbered lists
- Generic, textbook-like language with no personal experience
- No hesitation words, no personal pronouns like "I did", "my team"
- Suspiciously perfect grammar and flow
- Uses phrases like "It's important to note", "In conclusion", "Furthermore"
- No specific personal examples or real metrics
- Too comprehensive and balanced for an interview answer

Return ONLY this JSON, no explanation:
{
  "isAI": <true or false>,
  "confidence": <number 0-100>,
  "reason": "<one sentence explanation>"
}`,
          },
        ],
        max_tokens: 200,
      }),
    });

    const json = await res.json();
    const text = json.choices?.[0]?.message?.content ?? "";
    const match = text.match(/\{[\s\S]*\}/);

    if (!match) {
      return NextResponse.json({ isAI: false, confidence: 0, reason: "Could not analyze" });
    }

    const result = JSON.parse(match[0]);
    return NextResponse.json(result);

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
