export const recentSessions = [
  {
    id: "session-today",
    date: "Today",
    role: "SDE Fresher",
    experience: "0-1 years",
    company: "Product Startup",
    score: 72,
    rank: 41,
    delta: "+26",
  },
  {
    id: "session-yesterday",
    date: "Yesterday",
    role: "SDE Fresher",
    experience: "0-1 years",
    company: "Product Startup",
    score: 65,
    rank: 67,
    delta: "+8",
  },
  {
    id: "session-3-days",
    date: "3 days ago",
    role: "SDE Fresher",
    experience: "0-1 years",
    company: "Product Startup",
    score: 58,
    rank: 75,
    delta: "-2",
  },
  {
    id: "session-5-days",
    date: "5 days ago",
    role: "Product Manager",
    experience: "Fresher",
    company: "Enterprise SaaS",
    score: 69,
    rank: 52,
    delta: "+12",
  },
  {
    id: "session-week",
    date: "1 week ago",
    role: "Operations",
    experience: "0-2 years",
    company: "Marketplace",
    score: 61,
    rank: 84,
    delta: "+5",
  },
  {
    id: "session-9-days",
    date: "9 days ago",
    role: "Data Analyst",
    experience: "Fresher",
    company: "Fintech",
    score: 74,
    rank: 38,
    delta: "+18",
  },
  {
    id: "session-12-days",
    date: "12 days ago",
    role: "SDE",
    experience: "3-6 years",
    company: "Product Company",
    score: 70,
    rank: 45,
    delta: "-3",
  },
  {
    id: "session-15-days",
    date: "15 days ago",
    role: "MBA",
    experience: "Fresher",
    company: "Consulting",
    score: 66,
    rank: 59,
    delta: "+9",
  },
  {
    id: "session-18-days",
    date: "18 days ago",
    role: "Product Manager",
    experience: "1-3 years",
    company: "Consumer App",
    score: 63,
    rank: 71,
    delta: "+4",
  },
  {
    id: "session-21-days",
    date: "21 days ago",
    role: "SDE Fresher",
    experience: "0-1 years",
    company: "Product Startup",
    score: 56,
    rank: 93,
    delta: "-7",
  },
];

const names = [
  ["Arjun Sharma", "NIT Trichy", "SDE"],
  ["Priya Menon", "IIT Bombay", "Product Manager"],
  ["Rohit Verma", "BITS Pilani", "SDE"],
  ["Sneha Kapoor", "IIT Delhi", "Operations"],
  ["Karthik Iyer", "PSG Tech", "SDE"],
  ["Ananya Rao", "IIT Bombay", "MBA"],
  ["Rahul Nair", "SRM Chennai", "SDE Fresher"],
  ["Ishaan Mehta", "IIT Delhi", "Product Manager"],
  ["Devika Pillai", "BITS Goa", "Operations"],
  ["Aditya Reddy", "NIT Warangal", "SDE"],
  ["Meera Krishnan", "VIT Vellore", "Data Analyst"],
  ["Vikram Bose", "IIT Roorkee", "SDE"],
  ["Neha Agarwal", "NIT Calicut", "Product Manager"],
  ["Aman Choudhary", "Manipal", "Operations"],
  ["Riya Kulkarni", "IIT Madras", "MBA"],
  ["Dev Saxena", "IIIT Hyderabad", "SDE"],
  ["Pooja Bhat", "Delhi University", "Data Analyst"],
  ["Nikhil Malhotra", "BITS Hyderabad", "SDE Fresher"],
  ["Tanvi Sharma", "Christ University", "Product Manager"],
  ["Harsh Menon", "NIT Surat", "Operations"],
];

export const leaderboardEntries = Array.from({ length: 250 }, (_, index) => {
  const base = names[index % names.length];
  const rank = index + 1;
  const score = Math.max(48, 96 - Math.floor(index * 0.19));
  const isUser = rank === 41;

  return {
    rank,
    name: isUser ? "You" : base[0],
    college: isUser ? "Your college" : base[1],
    role: isUser ? "SDE Fresher" : base[2],
    score: isUser ? 72 : score,
    sessions: 1 + ((index * 3) % 12),
    delta: rank % 5 === 0 ? "-2" : `+${(index % 9) + 1}`,
    isUser,
  };
});

export const scoreDimensions = [
  { label: "Clarity", score: 72 },
  { label: "Structure", score: 58 },
  { label: "Confidence", score: 81 },
  { label: "Depth", score: 64 },
];
